### ISSUE TITLE
Mask field is always dirty

### ISSUE THREAD

**Issue by mfilteau** [notchris/payload-mask-plugin#1]
Editing a collection with a mask text field causes the collection document to be marked as dirty.
Payload will ask if we want to stay on the page or discard the changes.

The problem lies in the onAccept callback that is triggered when the field value is loaded.

Here's how I fix it:

```
onAccept={newValue => newValue !== value && setValue(newValue)}
```

**Comment by notchris** [comment]
@mfilteau So sorry I just saw all of these issues, I was on vacation. I will try to resolve them this week.

**Comment by mfilteau** [comment]
@notchris No worries!

**Comment by notchris** [comment]
This should be fixed now!
