### ISSUE TITLE
Ability to store the unmasked value

### ISSUE THREAD

**Issue by mfilteau** [notchris/payload-mask-plugin#3]
I have a phone number field with the following mask '(000) 000-0000'.

The IMaskInput component has an option to store the unmasked value (unmask) but this option is not available.

It would be nice to store values that don't have to be formatted later on.

**Comment by notchris** [comment]
@mfilteau I believe it does save the unmasked value to the record. Are you saying it would be nice to store the masked value "(000) 000-0000"? I could add a "saveMaskedValue" option?

<img width="727" alt="Screenshot 2024-07-15 at 1 49 08 PM" src="https://github.com/user-attachments/assets/dc8c3242-f9e3-4fdb-bdaa-f3cfeadc90af">
<img width="524" alt="Screenshot 2024-07-15 at 1 49 15 PM" src="https://github.com/user-attachments/assets/b26370eb-1b0a-432f-8bc8-052f3ac07180">

**Comment by mfilteau** [comment]
The saveMaskedValue option would be great. Saving the masked value (instead of the 'unmasked' value) makes life easier later on when the field needs to be displayed or used.

**Comment by notchris** [comment]
@mfilteau This should work as an option now!
